Account dashboard, notifications without data
unicef/atrium pull request #34
Opened 2021-04-29 11:11 UTC by victor11555

2021-04-29 12:15 UTC, NilsonBertola approved these changes, later dismissed

2021-04-29 12:41 UTC, veiga91 commented on packages/app/client/src/ui/pages/Account/components/BorderedInfo.js
> +      ].join(' ')}
There is a module named "classes" it could be easier than manipulates and then join

2021-04-29 12:43 UTC, veiga91 commented on packages/app/client/src/ui/pages/Account/components/Dashboard.js
> +                  <div style={{ borderBottom: '2.2px solid #15B54A' }} />
You could use the Box component from Material UI for this purpose

2021-04-29 12:45 UTC, veiga91 commented on packages/app/client/src/ui/pages/Account/components/Dashboard.js
> +                    <img style={{ marginRight: '5%' }} src={Like} />
You could use the LikeButton in the atoms folder if it is different from your goal please feel free do improve it

2021-04-29 12:46 UTC, veiga91 commented on packages/app/client/src/ui/pages/Account/components/Dashboard.js
> +                    <div style={{ borderBottom: '2.2px solid #15B54A' }} />
You could use the Box component from Material UI for this purpose

2021-04-29 12:48 UTC, veiga91 commented on packages/app/client/src/ui/pages/Account/components/Dashboard.js
> +                    style={{ width: '14px', marginRight: '15%' }}
There is a component for Images in the atoms folder, verify If it fits for this implementation purposes and feel free to improve it if you need

2021-04-29 12:53 UTC, veiga91 commented
Something happened and now I see my commits. After solving this I will return to finish the review

2021-04-29 13:42 UTC, veiga91 commented on packages/app/client/src/ui/molecules/VerticalTabs.js
> +          <Tab className={classes.tab} label="My Comments" />
I think this part could be more generic because all tab labels and the quantity of them are already defined.

2021-04-29 13:44 UTC, veiga91 commented on packages/app/client/src/ui/pages/Account/components/Dashboard.js
> +              <div style={{ width: '100%', height: '150px' }}>
You could use the Box component from Material UI for this purpose and avoid the inline styling

2021-04-29 13:47 UTC, veiga91 commented on packages/app/client/src/ui/pages/Account/components/Notifications.js
> +      <div style={{ borderBottom: '1px solid #E7E7E7', width: '100%' }} />
You could use the Box component the makeStyles function from Material UI for this purpose and avoid the inline styling

2021-04-29 13:48 UTC, veiga91 commented on packages/app/client/src/ui/pages/Account/components/Notifications.js
> +      <Typography style={{ margin: '5% 0', width: '81%' }} variant="body1">
You could use the classes for this styling

2021-04-29 13:56 UTC, veiga91 commented on packages/app/client/src/ui/pages/Account/components/VerticalTabs.js
> +import React, { useState } from 'react'
Is this the same component that is in the molecules folder?

2021-04-29 14:00 UTC, veiga91 commented on packages/app/client/src/ui/pages/Account/components/NotificationsActivity.js
> +      <Typography style={{ fontSize: '18px', margin: '3% 0' }} variant="h3">
Let's try to avoid inline styling when possible because it difficult the readability and the maintenance

2021-04-29 14:02 UTC, veiga91 commented on packages/app/client/src/ui/pages/Account/index.js
> +  const user = useSelector(state => state.auth.user)
Could you use a selector?

2021-04-29 14:03 UTC, veiga91 commented on packages/app/client/src/ui/pages/Account/index.js
> +    <Container className={containerStyle}>
Could you change for the MainContainer component in the templates folder ?

2021-04-29 14:27 UTC, NilsonBertola requested changes
waiting changes from @veiga91 comments

2021-04-29 15:55 UTC, veiga91 commented on packages/app/client/src/ui/molecules/VerticalTabs.js
> +            <Tab className={classes.tab} label={tab} />
The key property is missing. It is a good practice to use them.
https://reactjs.org/docs/lists-and-keys.html#keys

2021-04-29 16:01 UTC, veiga91 commented on packages/app/client/src/ui/pages/Account/components/Notifications.js
> +            checked: classes.checked
This component could be extracted and be shared with the NotificationsActivity, they seem very similar in their styles

2021-04-29 16:01 UTC, veiga91 commented on packages/app/client/src/ui/pages/Account/index.js
> +  const user = useSelector(state => state.auth.user)
Please, use selectors

2021-04-30 08:59 UTC, veiga91 commented on packages/app/client/src/ui/molecules/VerticalTabs.js
> +  const user = useSelector(state => state.auth.user)
Could you use a selector?

2021-04-30 10:24 UTC, veiga91 commented on packages/app/client/src/ui/atoms/Image.js
> +const Image = ({ height, width, sameSize, objectFit, children, borderRadius = 5, ...props}) => {
Could you could  use the Image.defaultProps  to use borderRadius default value, please ?

2021-04-30 11:02 UTC, veiga91 commented on packages/app/client/src/ui/pages/Account/components/Notifications.js
> +  },
Is it the same style applied in NotificationsActivity ? I think it will be a good idea make it shared between this two components

2021-04-30 12:56 UTC, veiga91 approved these changes

2021-05-03 08:51 UTC, NilsonBertola approved these changes

2021-05-03 08:52 UTC, merged