Comments router, add reply, get comments/replies
unicef/atrium pull request #44
Opened 2021-05-07 15:32 UTC by victor11555

2021-05-10 10:36 UTC, veiga91 commented on packages/app/routes/api/comments.js
> +  passport.authenticate('jwt', { session: false }),
is this route a public one?

2021-05-12 10:54 UTC, veiga91 commented on packages/app/routes/api/comments.js
> +      if (req.query.sort === 'asc') {
should we be using JS to do this manipulation?

2021-05-12 11:11 UTC, NilsonBertola approved these changes

2021-05-12 11:15 UTC, veiga91 approved these changes

2021-05-12 11:27 UTC, veiga91 commented on packages/app/routes/api/comments.js
> +            ? -1
I did not get it. Why are you verifying the opposite of "a.likes.length" is greater than "b.likes.length"? if you want to exclude the equals possibility you could use >= or <=

2021-05-12 11:31 UTC, veiga91 commented on packages/app/routes/api/comments.js
> +            ? -1
You could use "a.likes.length - b.likes.length" as well instead of this logic.

2021-05-12 11:34 UTC, veiga91 requested changes
Regarding my last comment, could you review the logic? I think it could be put in a simple way.

2021-05-12 13:03 UTC, veiga91 approved these changes

2021-05-12 13:10 UTC, merged